import os

target = 'aqdrivers'
sources = [Glob('dram/*.cc'), Glob('serial/*.cc')]
prefix='h8300-elf-'

env = Environment(CXX=prefix+'g++')
env['AR']=prefix+'ar'
env['RANLIB']=prefix+'ranlib'
env.Append(ENV={'PATH' : os.environ['PATH']})
env.Append(CCFLAGS='-Wall -Wextra -Werror -Os')
env.Append(CCFLAGS='-mh -nostdinc -nostdlib -nostartfiles -fno-builtin -ffreestanding')
env.Append(CCFLAGS='-std=c++11 -nostdinc++')
env.Append(CCFLAGS='-fno-use-cxa-atexit -fno-rtti -fno-exceptions -fno-threadsafe-statics')
env.Append(CPPPATH=['../include/'])
env.Append(CPPDEFINES=['AQ_CLOCK_20M', 'AQ_DRIVERS'])
env.StaticLibrary(target, sources)
