#ifndef AQ_H8_INTERRUPT_ID_H_
#define AQ_H8_INTERRUPT_ID_H_

#define AQ_INTERRUPT_NMI     7
#define AQ_INTERRUPT_TRAP0   8
#define AQ_INTERRUPT_TRAP1   9
#define AQ_INTERRUPT_TRAP2   10
#define AQ_INTERRUPT_TRAP3   11
#define AQ_INTERRUPT_IRQ0    12
#define AQ_INTERRUPT_IRQ1    13
#define AQ_INTERRUPT_IRQ2    14
#define AQ_INTERRUPT_IRQ3    15
#define AQ_INTERRUPT_IRQ4    16
#define AQ_INTERRUPT_IRQ5    17
#define AQ_INTERRUPT_WOVI    20
#define AQ_INTERRUPT_CMI     21
#define AQ_INTERRUPT_ADI     23
#define AQ_INTERRUPT_IMIA0   24
#define AQ_INTERRUPT_IMIB0   25
#define AQ_INTERRUPT_OVI0    26
#define AQ_INTERRUPT_IMIA1   28
#define AQ_INTERRUPT_IMIB1   29
#define AQ_INTERRUPT_OVI1    30
#define AQ_INTERRUPT_IMIA2   32
#define AQ_INTERRUPT_IMIB2   33
#define AQ_INTERRUPT_OVI2    34
#define AQ_INTERRUPT_CMIA0   36 
#define AQ_INTERRUPT_CMIB0   37
#define AQ_INTERRUPT_CMIAB1  38
#define AQ_INTERRUPT_TOVI01  39
#define AQ_INTERRUPT_CMIA2   40
#define AQ_INTERRUPT_CMIB2   41
#define AQ_INTERRUPT_CMIAB3  42
#define AQ_INTERRUPT_TOVI23  43
#define AQ_INTERRUPT_DEND0A  44
#define AQ_INTERRUPT_DEND0B  45
#define AQ_INTERRUPT_DEND1A  46
#define AQ_INTERRUPT_DEND1B  47
#define AQ_INTERRUPT_ERI0    52
#define AQ_INTERRUPT_RXI0    53
#define AQ_INTERRUPT_TXI0    54
#define AQ_INTERRUPT_TEI0    55
#define AQ_INTERRUPT_ERI1    56
#define AQ_INTERRUPT_RXI1    57
#define AQ_INTERRUPT_TXI1    58
#define AQ_INTERRUPT_TEI1    59
#define AQ_INTERRUPT_ERI2    60
#define AQ_INTERRUPT_RXI2    61
#define AQ_INTERRUPT_TXI2    62
#define AQ_INTERRUPT_TEI2    63
#define AQ_INTERRUPT_RESERVE -1

#endif
