#ifndef AQ_H8_MEMORY_MAP_H_
#define AQ_H8_MEMORY_MAP_H_

#define AQ_ROM_START 0x000000
#define AQ_ROM_SIZE  0x080000
#define AQ_ROM_END   (AQ_ROM_START + AQ_ROM_SIZE)

#define AQ_VECTOR_START 0x000000
#define AQ_VECTOR_SIZE  0x000100
#define AQ_VECTOR_END   (AQ_VECTOR_START + AQ_VECTOR_SIZE)

#define AQ_RAM_START 0xffbf20
#define AQ_RAM_SIZE  0x004000
#define AQ_RAM_END   (AQ_RAM_START + AQ_RAM_SIZE)

#define AQ_SOFT_VECTOR_START AQ_RAM_START
#define AQ_SOFT_VECTOR_SIZE  0x000040
#define AQ_SOFT_VECTPR_END   (AQ_SOFT_VECTOR_START + AQ_SOFT_VECTOR_SIZE)

#define AQ_DRAM_START 0x400000
#define AQ_DRAM_SIZE  0x200000
#define AQ_DRAM_END   (AQ_DRAM_START + AQ_DRAM_SIZE)

#endif
